// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3AzdRT4lmO_hi3uVw4NbNG7EfVS91DtA',
    appId: '1:703443835189:web:3e4805807569ea42aa947c',
    messagingSenderId: '703443835189',
    projectId: 'emapas-sacaba',
    authDomain: 'emapas-sacaba.firebaseapp.com',
    storageBucket: 'emapas-sacaba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1WYlQzUI-YaHPDqqYzUvKclV9LxWU3E',
    appId: '1:703443835189:android:a5ee5662bf1698d6aa947c',
    messagingSenderId: '703443835189',
    projectId: 'emapas-sacaba',
    storageBucket: 'emapas-sacaba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdi8Y5IONh9AkQA_FL8B4kDVyUrLqKKY8',
    appId: '1:703443835189:ios:39b01acdf0a68026aa947c',
    messagingSenderId: '703443835189',
    projectId: 'emapas-sacaba',
    storageBucket: 'emapas-sacaba.firebasestorage.app',
    iosBundleId: 'com.emapas.emapassacaba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdi8Y5IONh9AkQA_FL8B4kDVyUrLqKKY8',
    appId: '1:703443835189:ios:39b01acdf0a68026aa947c',
    messagingSenderId: '703443835189',
    projectId: 'emapas-sacaba',
    storageBucket: 'emapas-sacaba.firebasestorage.app',
    iosBundleId: 'com.emapas.emapassacaba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3AzdRT4lmO_hi3uVw4NbNG7EfVS91DtA',
    appId: '1:703443835189:web:3e3183db972c4610aa947c',
    messagingSenderId: '703443835189',
    projectId: 'emapas-sacaba',
    authDomain: 'emapas-sacaba.firebaseapp.com',
    storageBucket: 'emapas-sacaba.firebasestorage.app',
  );
}
